### PR TITLE
Add track limit and announce playlist

### PR DESCRIPTION
**Pull request by napstr**
Related to https://github.com/Frederikam/FredBoat/pull/90

### CODE REVIEW

**Comment by Frederikam** [comment]
Are these two strings exclusive to Spotify? If so, can you change te keys and values to explicitly state that? I don't want to confuse users or translators.

**Comment by napstr** [comment]
They are also used by the paste service playlist importer..

**Comment by napstr** [comment]
More specific: The loader tries to identify a link as a (long loading) playlist and if it is,  will post the loadAnnouncePlaylist. 

The queue limit String was in the code already (it's the one being displayed when the player refuses to add more songs when the already has 10000), I'm just using the chance to i18n it.

**Comment by Frederikam** [comment]
This could be moved to a different branch

**Comment by napstr** [comment]
I c

I was trying to push to master

https://puu.sh/vtMme/8f31013f02.png

**Comment by napstr** [comment]
Can be found here now: https://github.com/Frederikam/FredBoat-i13n/tree/spotifyplaylist

**Pull request closed without merging**
